# Install packages
install.packages("renv")
install.packages("reshape2")
install.packages("recommenderlab")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("knitr", dependencies = TRUE)
install.packages("vegan")
install.packages("coop")
install.packages("bench")
install.packages("gridExtra")
install.packages("testthat")
install.packages("devtools", type = "win.binary")
install.packages("rcmdcheck", type = "win.binary")
install.packages("fmsb")